name: $(Build.BuildId)

variables:
  AppVersion: '1.0.[yyyyWW].*'
  TestFilter: '82100..82150'
  dockerimage: mcr.microsoft.com/businesscentral/sandbox

steps:
- task: ALOpsDockerStart@1
  inputs:
    docker_image: $(dockerimage)
    docker_pull: true
    docker_login: 'Insider Docker Registry'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bc.license)
    
- task: ALOpsAppCompiler@1
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)
    failed_on_warnings: true    

- task: ALOpsAppPublish@1
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

# - task: ALOpsAppTest@1
#   displayName: 'Run TestSuite'
#   inputs:
#     usedocker: true
#     import_action: "Skip"
#     testfilter: $(TestFilter)
#     show_available_tests: true
#   continueOnError: true    

# - task: PublishTestResults@1
#   displayName: 'Publish Test Results **/TestResults.xml'
#   inputs:
#     testResultsFormat: XUnit
#     testResultsFiles: '**/TestResults.xml'
#     testRunTitle: 'BC Test Results: $(Build.BuildId)'

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()
  inputs:
    docker_login: 'Insider Docker Registry'

- task: PublishBuildArtifacts@1
  enabled: false
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Base'
    publishLocation: 'Container'